name: Load Credentials through GitHub Actions

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to load credentials for"
        required: true
        default: "prd"

  pull_request:
    branches:
      - main

  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  Load-Credentials:
    uses: EliLillyCo/hangar/.github/workflows/load-credentials.yaml@main
    with:
      environment: ${{ github.event.inputs.environment || 'prd' }}
